add check to make sure SHA is unchanged

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -28,6 +28,11 @@ jobs:
       - run: |
           pip install build twine
           ./build_dist.py
+          if [[ -n "$(git status --porcelain)" ]]
+          then
+            echo "::error cannot publish release, commited SHA does not match build SHA"
+            exit 1
+          fi
       - name: upload test distribution
         uses: pypa/gh-action-pypi-publish@release/v1
         if: ${{ inputs.is_test }}
