test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -24,169 +24,154 @@ jobs:
     env:
       REGISTRY: us-east4-docker.pkg.dev/weave-support-367421/weave-images
     needs: check-which-tests-to-run
-    if: github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_query_tests
+
+    # if: github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_query_tests
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 2
 
+      - name: Check if build is needed
+        id: build_check
+        run: |
+          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ needs.check-which-tests-to-run.outputs.weave_query_tests }}" == "true" ]]; then
+            echo "Build is needed"
+            echo "build_needed=true" >> $GITHUB_OUTPUT
+          else
+            echo "Build is not needed"
+            echo "build_needed=false" >> $GITHUB_OUTPUT
+          fi
+
       - name: Login to Docker Hub
+        if: steps.build_check.outputs.build_needed == 'true'
         uses: docker/login-action@v2
         with:
           registry: us-east4-docker.pkg.dev
           username: _json_key
           password: ${{ secrets.gcp_sa_key }}
 
-      # this script is hardcoded to build for linux/amd64
       - name: Prune docker cache
+        if: steps.build_check.outputs.build_needed == 'true'
         run: docker system prune -f
-      - name: Build legacy (query sevice) unit test image
+
+      - name: Build legacy (query service) unit test image
+        if: steps.build_check.outputs.build_needed == 'true'
         run: python3 weave/docker/docker_build.py build_deps weave-test-python-query-service builder . weave_query/Dockerfile.ci.test
 
-  build-container-query-service-dummy:
-    name: 'SKIPPED: Build Legacy (Query Service) test container'
-    if: github.ref != 'refs/heads/master' && !needs.check-which-tests-to-run.outputs.weave_query_tests
-    runs-on: ubuntu-latest
-    steps:
-      - run: |
-          echo "Skipping build-container-query-service-dummy"
+  # test-query-service:
+  #   name: Legacy (Query Service) Python unit tests
+  #   timeout-minutes: 15 # do not raise! running longer than this indicates an issue with the tests. fix there.
+  #   needs:
+  #     - check-which-tests-to-run
+  #     - build-container-query-service
+  #   # runs-on: [self-hosted, gke-runner]
+  #   runs-on: ubuntu-latest
+  #   if: github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_query_tests
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       job_num: [0, 1]
+  #   # runs-on: ubuntu-latest
+  #   container: us-east4-docker.pkg.dev/weave-support-367421/weave-images/weave-test-python-query-service:${{ github.sha }}
+  #   services:
+  #     wandbservice:
+  #       image: us-central1-docker.pkg.dev/wandb-production/images/local-testcontainer:master
+  #       credentials:
+  #         username: _json_key
+  #         password: ${{ secrets.gcp_wb_sa_key }}
+  #       env:
+  #         CI: 1
+  #         WANDB_ENABLE_TEST_CONTAINER: true
+  #       ports:
+  #         - '8080:8080'
+  #         - '8083:8083'
+  #         - '9015:9015'
+  #       options: --health-cmd "curl --fail http://localhost:8080/healthz || exit 1" --health-interval=5s --health-timeout=3s
+  #   steps:
+  #     # - uses: datadog/agent-github-action@v1.3
+  #     #   with:
+  #     #     api_key: ${{ secrets.DD_API_KEY }}
+  #     - uses: actions/checkout@v2
+  #     - name: Verify wandb server is running
+  #       run: curl -s http://wandbservice:8080/healthz
+  #     - name: Run Legacy (Query Service) Python Unit Tests
+  #       env:
+  #         DD_SERVICE: weave-python
+  #         DD_ENV: ci
+  #         WEAVE_SENTRY_ENV: ci
+  #         CI: 1
+  #         WB_SERVER_HOST: http://wandbservice
+  #         WEAVE_SERVER_DISABLE_ECOSYSTEM: 1
+  #       run: |
+  #         source /root/venv/bin/activate && \
+  #         cd weave_query && \
+  #         pytest \
+  #         --job-num=${{ matrix.job_num }} \
+  #         --timeout=90 \
+  #         --ddtrace \
+  #         --durations=5 \
+  #         .
 
-  build-container-query-service-matrix-check: # This job does nothing and is only used for the branch protection
-    if: always()
-    needs:
-      - check-which-tests-to-run
-      - ${{ (github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_query_tests) && 'build-container-query-service' || 'build-container-query-service-dummy' }}
+  # test-query-service-matrix-check: # This job does nothing and is only used for the branch protection
+  #   if: always()
 
-    runs-on: ubuntu-latest
+  #   needs:
+  #     - test-query-service
 
-    steps:
-      - name: Passes if all test-query-service jobs succeeded
-        uses: re-actors/alls-green@release/v1
-        with:
-          jobs: ${{ toJSON(needs) }}
+  #   runs-on: ubuntu-latest
 
-  test-query-service:
-    name: Legacy (Query Service) Python unit tests
-    timeout-minutes: 15 # do not raise! running longer than this indicates an issue with the tests. fix there.
-    needs:
-      - check-which-tests-to-run
-      - build-container-query-service
-    # runs-on: [self-hosted, gke-runner]
-    runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_query_tests
-    strategy:
-      fail-fast: false
-      matrix:
-        job_num: [0, 1]
-    # runs-on: ubuntu-latest
-    container: us-east4-docker.pkg.dev/weave-support-367421/weave-images/weave-test-python-query-service:${{ github.sha }}
-    services:
-      wandbservice:
-        image: us-central1-docker.pkg.dev/wandb-production/images/local-testcontainer:master
-        credentials:
-          username: _json_key
-          password: ${{ secrets.gcp_wb_sa_key }}
-        env:
-          CI: 1
-          WANDB_ENABLE_TEST_CONTAINER: true
-        ports:
-          - '8080:8080'
-          - '8083:8083'
-          - '9015:9015'
-        options: --health-cmd "curl --fail http://localhost:8080/healthz || exit 1" --health-interval=5s --health-timeout=3s
-    steps:
-      # - uses: datadog/agent-github-action@v1.3
-      #   with:
-      #     api_key: ${{ secrets.DD_API_KEY }}
-      - uses: actions/checkout@v2
-      - name: Verify wandb server is running
-        run: curl -s http://wandbservice:8080/healthz
-      - name: Run Legacy (Query Service) Python Unit Tests
-        env:
-          DD_SERVICE: weave-python
-          DD_ENV: ci
-          WEAVE_SENTRY_ENV: ci
-          CI: 1
-          WB_SERVER_HOST: http://wandbservice
-          WEAVE_SERVER_DISABLE_ECOSYSTEM: 1
-        run: |
-          source /root/venv/bin/activate && \
-          cd weave_query && \
-          pytest \
-          --job-num=${{ matrix.job_num }} \
-          --timeout=90 \
-          --ddtrace \
-          --durations=5 \
-          .
+  #   steps:
+  #     - name: Passes if all test-query-service jobs succeeded
+  #       uses: re-actors/alls-green@release/v1
+  #       with:
+  #         jobs: ${{ toJSON(needs) }}
 
-  test-query-service-dummy:
-    name: 'SKIPPED: Legacy (Query Service) Python unit tests'
-    if: github.ref != 'refs/heads/master' && !needs.check-which-tests-to-run.outputs.weave_query_tests
-    runs-on: ubuntu-latest
-    steps:
-      - run: |
-          echo "Skipping build-container-query-service-dummy"
+  # # ==== Weave UI Jobs ====
+  # weavejs-lint-compile:
+  #   name: WeaveJS Lint and Compile
+  #   runs-on: ubuntu-latest
+  #   needs: check-which-tests-to-run
+  #   if: github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_js_tests
+  #   # runs-on: [self-hosted, gke-runner]
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #       with:
+  #         fetch-depth: 0
+  #         token: ${{ secrets.GITHUB_TOKEN }}
+  #     - uses: actions/setup-node@v1
+  #       with:
+  #         node-version: '18.x'
+  #     - run: |
+  #         set -e
+  #         cd weave-js
+  #         yarn install --frozen-lockfile
+  #         yarn generate
+  #         yarn eslint --max-warnings=0
+  #         yarn tslint
+  #         yarn prettier
+  #         yarn run tsc
 
-  test-query-service-matrix-check: # This job does nothing and is only used for the branch protection
-    if: always()
-    needs:
-      - check-which-tests-to-run
-      - ${{ (github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_query_tests) && 'test-query-service' || 'test-query-service-dummy' }}
+  # weavejs-lint-compile-dummy:
+  #   name: 'SKIPPED: WeaveJS Lint and Compile'
+  #   if: github.ref != 'refs/heads/master' && !needs.check-which-tests-to-run.outputs.weave_js_tests
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - run: |
+  #         echo "Skipping build-container-query-service-dummy"
 
-    runs-on: ubuntu-latest
+  # weavejs-lint-compile-matrix-check: # This job does nothing and is only used for the branch protection
+  #   if: always()
+  #   needs:
+  #     - check-which-tests-to-run
+  #     - ${{ (github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_js_tests) && 'weavejs-lint-compile' || 'weavejs-lint-compile-dummy' }}
 
-    steps:
-      - name: Passes if all test-query-service jobs succeeded
-        uses: re-actors/alls-green@release/v1
-        with:
-          jobs: ${{ toJSON(needs) }}
+  #   runs-on: ubuntu-latest
 
-  # ==== Weave UI Jobs ====
-  weavejs-lint-compile:
-    name: WeaveJS Lint and Compile
-    runs-on: ubuntu-latest
-    needs: check-which-tests-to-run
-    if: github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_js_tests
-    # runs-on: [self-hosted, gke-runner]
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          token: ${{ secrets.GITHUB_TOKEN }}
-      - uses: actions/setup-node@v1
-        with:
-          node-version: '18.x'
-      - run: |
-          set -e
-          cd weave-js
-          yarn install --frozen-lockfile
-          yarn generate
-          yarn eslint --max-warnings=0
-          yarn tslint
-          yarn prettier
-          yarn run tsc
-
-  weavejs-lint-compile-dummy:
-    name: 'SKIPPED: WeaveJS Lint and Compile'
-    if: github.ref != 'refs/heads/master' && !needs.check-which-tests-to-run.outputs.weave_js_tests
-    runs-on: ubuntu-latest
-    steps:
-      - run: |
-          echo "Skipping build-container-query-service-dummy"
-
-  weavejs-lint-compile-matrix-check: # This job does nothing and is only used for the branch protection
-    if: always()
-    needs:
-      - check-which-tests-to-run
-      - ${{ (github.ref == 'refs/heads/master' || needs.check-which-tests-to-run.outputs.weave_js_tests) && 'weavejs-lint-compile' || 'weavejs-lint-compile-dummy' }}
-
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Passes if all weavejs-lint-compile jobs succeeded
-        uses: re-actors/alls-green@release/v1
-        with:
-          jobs: ${{ toJSON(needs) }}
+  #   steps:
+  #     - name: Passes if all weavejs-lint-compile jobs succeeded
+  #       uses: re-actors/alls-green@release/v1
+  #       with:
+  #         jobs: ${{ toJSON(needs) }}
 
   # ==== Trace Jobs ====
   lint:
